it.skip('code challenge', () => {
    cy.visit("https://www.google.com/")
  })
it('code challenge', () => {
    cy.visit("https://www.saucedemo.com/")
    cy.get('[data-test="username"]')
    .type(`standard_user`)
    cy.get('#password')
    .type('secret_sauce')
    cy.contains("Login").click()
    cy.get("button.btn_inventory").eq(0)
    .should('have.text','Add to cart')
    cy.get("button.btn_inventory").eq(0).click()
    cy.get("button.btn_inventory").eq(0)
    .should('have.text','Remove')
    cy.get("button.btn_inventory").eq(1).click()
    cy.get("a.shopping_cart_link").should("be.clickable")
    .click()
    cy.get("div.cart_item").should("have.value",2)
    cy.contains("Remove").click()
    cy.get("div.cart_item").should("have.value",1)
    cy.contains("Checkout").click()
  })